### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Slater-Victoroff** [jhorikawa/HoudiniHowtos#2]
This is awesome! Amazing that you've been putting these together for so many years.

This is a PSA to tell you that *technically* nobody is allowed to download, fork, or use this repo at present because it is missing a license. Look here for more info: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

If you're not sure what to use, the MIT license is a good default: https://opensource.org/license/mit

**Comment by jhorikawa** [comment]
@Slater-Victoroff 
Thank you for the comment. I have made the repo using MIT license so that anyone can use it for whatever purpose they have.
